# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Subhojyoti Mukherjee
tagline:          'Ph.D. at University of Massachusetts, Amherst'
description:      'UMass Amherst, IIT Madras'
url:              https://subhojyoti.github.io/
baseurl:          /

author:
  name:           'Subhojyoti Mukherjee'
  url:            https://subhojyoti.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Subhojyoti/subhojyoti.github.io
